
package Coleccion;

import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class FormaPrincipal extends javax.swing.JFrame {
    private int contador=0;
    Colecciones obj = new Colecciones(); //instanciar la clase, comunicacion con la clase secundaria
    DefaultListModel modelo = new DefaultListModel(); //modelo para pasarlo al objeto, usarlo en listas
    DefaultListModel modeloArray = new DefaultListModel(); //modelo para pasarlo al objeto, usarlo en listas
    DefaultListModel modeloLinked = new DefaultListModel(); //modelo para pasarlo al objeto, usarlo en listas
    ArrayList<Double> arrayL = new ArrayList<Double>();
    LinkedList<Double> linked = new LinkedList<Double>();
    public FormaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextNum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNumeros = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListArray = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListLinked = new javax.swing.JList<>();
        Ordenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNumKeyTyped(evt);
            }
        });

        jLabel1.setText("Número ");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListNumeros);

        jScrollPane2.setViewportView(jListArray);

        jScrollPane3.setViewportView(jListLinked);

        Ordenar.setText("Ordenar");
        Ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(jTextNum, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(Ordenar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(Ordenar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (contador !=10) //contador es diferente a la cantidad de 10 numeros
        { if(obj.asignar(Double.parseDouble(jTextNum.getText()))){ //confirmar el numero 
            modelo.addElement(jTextNum.getText());//cargarlo en prelista
            
            jListNumeros.setModel(modelo); //enviarlo para imprimirlo en el list
            contador++;
        }
        else{
            JOptionPane.showMessageDialog(null, "Ya se encuentra agregado el numero");
        }   
        }
        else{
             JOptionPane.showMessageDialog(null, "Solo se permiten 10 números");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNumKeyTyped
       char car= evt.getKeyChar();
       if((car<'0'|| car>'9') && (car<','|| car>'.'))evt.consume(); //dato debe ser entre 9 y 0 y debe admitir el punto y la coma
       
    }//GEN-LAST:event_jTextNumKeyTyped

    private void OrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenarActionPerformed
        arrayL=obj.ordenarArrayList(); //ordenar arraylist y pasarlo a la variable arrayL
        linked=obj.ordenarLinkedList(); //ordenar linkedList y pasarlo a la variable linked
        modeloArray.removeAllElements(); //borrar lista anterior
        modeloLinked.removeAllElements(); //borrar lista anterior
        for(int i=0; i<linked.size(); i++){ //introducir uno por uno
            modeloArray.addElement(arrayL.get(i));
            modeloLinked.addElement(linked.get(i));
        }  
        jListArray.setModel(modeloArray); //pasar modelo a las listas
        jListLinked.setModel(modeloLinked);
    }//GEN-LAST:event_OrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ordenar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListArray;
    private javax.swing.JList<String> jListLinked;
    private javax.swing.JList<String> jListNumeros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextNum;
    // End of variables declaration//GEN-END:variables
}
